# Generated by Django 2.2 on 2020-07-10 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200709_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notion',
            options={'ordering': ['-id']},
        ),
    ]
