# Generated by Django 2.2.13 on 2020-07-11 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0004_notion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='notion_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TweetLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Notion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
