# Generated by Django 2.2.13 on 2020-07-11 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200711_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notion',
            name='likes',
        ),
    ]
