# Generated by Django 2.2.13 on 2020-07-11 22:33

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200711_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='notion',
            name='likes',
            field=models.ManyToManyField(
                related_name='notion_user', through='myapp.NotionLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
