# Generated by Django 2.2.13 on 2020-07-13 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200711_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='notion',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Notion'),
        ),
    ]
